# Building of a PostgreSQL container for database querying mocking
# Author: @ponchotitlan

# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Copy the initialization script to the Docker image
COPY init.sql /docker-entrypoint-initdb.d/